language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  include:
    - php: 5.5
      env: deps=highest
    - php: 5.6
      env: deps=lowest

before_install:
  - composer selfupdate
  - if [ -z "$deps" ]; then composer install --prefer-dist; fi;
  - if [ "$deps" = "lowest" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi;
  - if [ "$deps" = "highest" ]; then composer update --prefer-dist; fi;

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
