services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    contao_calendar.listener.event_picker_provider:
        class: Contao\CalendarBundle\Menu\EventPickerProvider
        public: false
        arguments:
            - "@router"
            - "@request_stack"
            - "@security.token_storage"
        tags:
            - { name: contao.picker_menu_provider, priority: 96 }
